---
driver:
  name: lxd
  image_server: https://cloud-images.ubuntu.com/releases
  config:
    security.nesting: true
#    security.privileged: true

provisioner:
  name: chef_zero
  multiple_converge: 2
  enforce_idempotency: true
  deprecations_as_errors: true
  downloads:
    /tmp/kitchen/nodes: .kitchen/artifacts

# verifier:
#   name: inspec

transport: lxd

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04
    driver:
      image_server: https://cloud-images.ubuntu.com/daily

suites:
  - name: lxd
    run_list:
      - test::default
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
