---
driver:
  name: lxd
  image_server: https://cloud-images.ubuntu.com/releases
  ssh_login: 'ubuntu'
  config:
    security.nesting: true
    security.privileged: true

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: lxd
    run_list:
      - lxd_nexus::default
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
